" ayu Vivid Dark for Vim and Neovim (truecolor, with 256-color fallback).
" Generated by build.ts from the ayu Vivid Dark Zed theme. Don't edit by hand.

hi clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'ayu-vivid-dark'
set background=dark
if has('termguicolors')
  set termguicolors
endif

hi Normal guifg=#bfbdb6 guibg=#10141c guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=233
hi NormalFloat guifg=#bfbdb6 guibg=#1e222a guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=235
hi FloatBorder guifg=#1b1f29 guibg=#1e222a guisp=NONE gui=NONE cterm=NONE ctermfg=234 ctermbg=235
hi FloatTitle guifg=#bfbdb6 guibg=#1e222a guisp=NONE gui=bold cterm=bold ctermfg=250 ctermbg=235
hi NonText guifg=#45474b guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=238 ctermbg=NONE
hi SpecialKey guifg=#45474b guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=238 ctermbg=NONE
hi Whitespace guifg=#45474b guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=238 ctermbg=NONE
hi EndOfBuffer guifg=#10141c guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=233 ctermbg=NONE
hi Conceal guifg=#5a6378 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=60 ctermbg=NONE
hi Comment guifg=#5a6673 guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=241 ctermbg=NONE
hi Constant guifg=#85eac9 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=115 ctermbg=NONE
hi String guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi Character guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi Number guifg=#eeb125 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=214 ctermbg=NONE
hi Boolean guifg=#eeb125 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=214 ctermbg=NONE
hi Float guifg=#eeb125 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=214 ctermbg=NONE
hi Identifier guifg=#bfbdb6 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=NONE
hi Function guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
hi Statement guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Conditional guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Repeat guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Label guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Operator guifg=#fd8f56 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=209 ctermbg=NONE
hi Keyword guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Exception guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi PreProc guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Include guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Define guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Macro guifg=#fe6370 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=203 ctermbg=NONE
hi PreCondit guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Type guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
hi StorageClass guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi Structure guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
hi Typedef guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
hi Special guifg=#ecbe7c guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
hi SpecialChar guifg=#85eac9 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=115 ctermbg=NONE
hi Tag guifg=#00bbed guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=38 ctermbg=NONE
hi Delimiter guifg=#8b8b88 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=245 ctermbg=NONE
hi SpecialComment guifg=#5a6673 guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=241 ctermbg=NONE
hi Debug guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
hi Underlined guifg=#59c2ff guibg=NONE guisp=NONE gui=underline cterm=underline ctermfg=75 ctermbg=NONE
hi Ignore guifg=#10141c guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=233 ctermbg=NONE
hi Error guifg=#d95757 guibg=NONE guisp=NONE gui=bold cterm=bold ctermfg=167 ctermbg=NONE
hi Todo guifg=#e6b450 guibg=NONE guisp=NONE gui=bold cterm=bold ctermfg=179 ctermbg=NONE
hi Cursor guifg=#10141c guibg=#e6b450 guisp=NONE gui=NONE cterm=NONE ctermfg=233 ctermbg=179
hi lCursor guifg=#10141c guibg=#e6b450 guisp=NONE gui=NONE cterm=NONE ctermfg=233 ctermbg=179
hi CursorIM guifg=#10141c guibg=#e6b450 guisp=NONE gui=NONE cterm=NONE ctermfg=233 ctermbg=179
hi CursorLine guifg=NONE guibg=#161a24 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=234
hi CursorColumn guifg=NONE guibg=#161a24 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=234
hi ColorColumn guifg=NONE guibg=#161a24 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=234
hi CursorLineNr guifg=#5a6378 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=60 ctermbg=NONE
hi LineNr guifg=#404758 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=238 ctermbg=NONE
hi SignColumn guifg=#404758 guibg=#10141c guisp=NONE gui=NONE cterm=NONE ctermfg=238 ctermbg=233
hi FoldColumn guifg=#404758 guibg=#10141c guisp=NONE gui=NONE cterm=NONE ctermfg=238 ctermbg=233
hi Folded guifg=#5a6378 guibg=#161a24 guisp=NONE gui=NONE cterm=NONE ctermfg=60 ctermbg=234
hi Visual guifg=NONE guibg=#193155 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=236
hi VisualNOS guifg=NONE guibg=#193155 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=236
hi Search guifg=NONE guibg=#2e2b21 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=236
hi IncSearch guifg=#10141c guibg=#e6b450 guisp=NONE gui=NONE cterm=NONE ctermfg=233 ctermbg=179
hi CurSearch guifg=#10141c guibg=#e6b450 guisp=NONE gui=NONE cterm=NONE ctermfg=233 ctermbg=179
hi Substitute guifg=#10141c guibg=#e6b450 guisp=NONE gui=NONE cterm=NONE ctermfg=233 ctermbg=179
hi MatchParen guifg=NONE guibg=#262c38 guisp=NONE gui=bold cterm=bold ctermfg=NONE ctermbg=236
hi QuickFixLine guifg=NONE guibg=#193155 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=236
hi StatusLine guifg=#bfbdb6 guibg=#1e222a guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=235
hi StatusLineNC guifg=#5a6378 guibg=#0d1017 guisp=NONE gui=NONE cterm=NONE ctermfg=60 ctermbg=233
hi TabLine guifg=#5a6378 guibg=#0d1017 guisp=NONE gui=NONE cterm=NONE ctermfg=60 ctermbg=233
hi TabLineSel guifg=#bfbdb6 guibg=#10141c guisp=NONE gui=bold cterm=bold ctermfg=250 ctermbg=233
hi TabLineFill guifg=NONE guibg=#0d1017 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=233
hi VertSplit guifg=#1b1f29 guibg=#10141c guisp=NONE gui=NONE cterm=NONE ctermfg=234 ctermbg=233
hi WinSeparator guifg=#1b1f29 guibg=#10141c guisp=NONE gui=NONE cterm=NONE ctermfg=234 ctermbg=233
hi WinBar guifg=#bfbdb6 guibg=#10141c guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=233
hi WinBarNC guifg=#5a6378 guibg=#10141c guisp=NONE gui=NONE cterm=NONE ctermfg=60 ctermbg=233
hi Pmenu guifg=#bfbdb6 guibg=#1e222a guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=235
hi PmenuSel guifg=#bfbdb6 guibg=#282e39 guisp=NONE gui=bold cterm=bold ctermfg=250 ctermbg=236
hi PmenuSbar guifg=NONE guibg=#1e222a guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=235
hi PmenuThumb guifg=NONE guibg=#303642 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=237
hi PmenuMatch guifg=#e6b450 guibg=#1e222a guisp=NONE gui=bold cterm=bold ctermfg=179 ctermbg=235
hi PmenuMatchSel guifg=#e6b450 guibg=#282e39 guisp=NONE gui=bold cterm=bold ctermfg=179 ctermbg=236
hi WildMenu guifg=#bfbdb6 guibg=#282e39 guisp=NONE gui=bold cterm=bold ctermfg=250 ctermbg=236
hi Directory guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
hi Title guifg=#a5dc01 guibg=NONE guisp=NONE gui=bold cterm=bold ctermfg=148 ctermbg=NONE
hi DiffAdd guifg=NONE guibg=#1e2d25 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=235
hi DiffChange guifg=NONE guibg=#1a2533 guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=235
hi DiffText guifg=NONE guibg=#293d55 guisp=NONE gui=bold cterm=bold ctermfg=NONE ctermbg=237
hi DiffDelete guifg=#af525d guibg=#271d25 guisp=NONE gui=NONE cterm=NONE ctermfg=131 ctermbg=234
hi diffAdded guifg=#61c33d guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=77 ctermbg=NONE
hi diffRemoved guifg=#ff5f71 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=203 ctermbg=NONE
hi diffChanged guifg=#73b8ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=111 ctermbg=NONE
hi diffFile guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi diffLine guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
hi Added guifg=#538c45 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=64 ctermbg=NONE
hi Changed guifg=#5587bb guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=67 ctermbg=NONE
hi Removed guifg=#af525d guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=131 ctermbg=NONE
hi GitGutterAdd guifg=#538c45 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=64 ctermbg=NONE
hi GitGutterChange guifg=#5587bb guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=67 ctermbg=NONE
hi GitGutterDelete guifg=#af525d guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=131 ctermbg=NONE
hi GitSignsAdd guifg=#538c45 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=64 ctermbg=NONE
hi GitSignsChange guifg=#5587bb guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=67 ctermbg=NONE
hi GitSignsDelete guifg=#af525d guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=131 ctermbg=NONE
hi SpellBad guifg=NONE guibg=NONE guisp=#d95757 gui=undercurl cterm=undercurl ctermfg=NONE ctermbg=NONE
hi SpellCap guifg=NONE guibg=NONE guisp=#59c2ff gui=undercurl cterm=undercurl ctermfg=NONE ctermbg=NONE
hi SpellRare guifg=NONE guibg=NONE guisp=#5a6673 gui=undercurl cterm=undercurl ctermfg=NONE ctermbg=NONE
hi SpellLocal guifg=NONE guibg=NONE guisp=#5a6673 gui=undercurl cterm=undercurl ctermfg=NONE ctermbg=NONE
hi ErrorMsg guifg=#d95757 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=167 ctermbg=NONE
hi WarningMsg guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
hi MoreMsg guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
hi Question guifg=#70bf56 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=106 ctermbg=NONE
hi ModeMsg guifg=#70bf56 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=106 ctermbg=NONE
hi jinjaVarBlock guifg=#ecbe7c guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
hi jinjaVariable guifg=#ecbe7c guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
hi jinjaAttribute guifg=#ecbe7c guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
hi jinjaVarDelim guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi jinjaFilter guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
hi jinjaTagBlock guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi jinjaTagDelim guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi jinjaStatement guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
hi jinjaOperator guifg=#fd8f56 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=209 ctermbg=NONE
hi jinjaComment guifg=#5a6673 guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=241 ctermbg=NONE
hi jinjaString guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi jinjaNumber guifg=#eeb125 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=214 ctermbg=NONE
hi ansibleModule guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi ansibleArgument guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi ansibleVariable guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi ansibleOption guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi yamlString guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi yamlFlowString guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi yamlSingleQuoted guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi yamlDoubleQuoted guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi yamlPlainScalar guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi yamlBlockString guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
hi yamlBlockScalarHeader guifg=#59c2ff guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=75 ctermbg=NONE
hi yamlAnchorName guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
hi yamlAlias guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
hi yamlComment guifg=#5a6673 guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=241 ctermbg=NONE

" Let Jinja highlight inside YAML block strings (ansible-vim). This only
" affects the buffer that is current when the colorscheme loads.
syn clear yamlBlockString
syn region yamlBlockString start=/^\z(\s\+\)/ skip=/^$/ end=/^\%(\z1\)\@!/ contained contains=@jinja

if has('nvim')
  hi @comment guifg=#5a6673 guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=241 ctermbg=NONE
  hi @comment.documentation guifg=#5a6673 guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=241 ctermbg=NONE
  hi @string guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
  hi @string.escape guifg=#85eac9 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=115 ctermbg=NONE
  hi @string.regexp guifg=#85eac9 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=115 ctermbg=NONE
  hi @string.regex guifg=#85eac9 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=115 ctermbg=NONE
  hi @string.special guifg=#85eac9 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=115 ctermbg=NONE
  hi @string.special.symbol guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
  hi @string.special.url guifg=#59c2ff guibg=NONE guisp=NONE gui=underline cterm=underline ctermfg=75 ctermbg=NONE
  hi @character guifg=#a5dc01 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=148 ctermbg=NONE
  hi @character.special guifg=#85eac9 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=115 ctermbg=NONE
  hi @number guifg=#eeb125 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=214 ctermbg=NONE
  hi @number.float guifg=#eeb125 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=214 ctermbg=NONE
  hi @float guifg=#eeb125 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=214 ctermbg=NONE
  hi @boolean guifg=#eeb125 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=214 ctermbg=NONE
  hi @constant guifg=#85eac9 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=115 ctermbg=NONE
  hi @constant.builtin guifg=#eeb125 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=214 ctermbg=NONE
  hi @constant.macro guifg=#85eac9 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=115 ctermbg=NONE
  hi @function guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @function.call guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @function.method guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @function.method.call guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @method guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @method.call guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @function.builtin guifg=#fe6370 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=203 ctermbg=NONE
  hi @function.macro guifg=#fe6370 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=203 ctermbg=NONE
  hi @constructor guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
  hi @keyword guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @keyword.function guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @keyword.return guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @keyword.conditional guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @keyword.repeat guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @keyword.exception guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @keyword.import guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @keyword.operator guifg=#fd8f56 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=209 ctermbg=NONE
  hi @keyword.directive guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @conditional guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @repeat guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @include guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @exception guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @operator guifg=#fd8f56 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=209 ctermbg=NONE
  hi @type guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
  hi @type.builtin guifg=#00bbed guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=38 ctermbg=NONE
  hi @type.definition guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
  hi @variable guifg=#bfbdb6 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=NONE
  hi @variable.builtin guifg=#00bbed guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=38 ctermbg=NONE
  hi @variable.parameter guifg=#d2a6ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=183 ctermbg=NONE
  hi @variable.member guifg=#bfbdb6 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=NONE
  hi @parameter guifg=#d2a6ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=183 ctermbg=NONE
  hi @field guifg=#bfbdb6 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=NONE
  hi @property guifg=#bfbdb6 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=NONE
  hi @module guifg=#bfbdb6 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=NONE
  hi @namespace guifg=#bfbdb6 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=NONE
  hi @label guifg=#ff8f40 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=208 ctermbg=NONE
  hi @attribute guifg=#ecbe7c guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @punctuation guifg=#8b8b88 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=245 ctermbg=NONE
  hi @punctuation.bracket guifg=#bfbdb6 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=250 ctermbg=NONE
  hi @punctuation.delimiter guifg=#8b8b88 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=245 ctermbg=NONE
  hi @punctuation.special guifg=#ecbe7c guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @tag guifg=#00bbed guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=38 ctermbg=NONE
  hi @tag.attribute guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @tag.delimiter guifg=#8b8b88 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=245 ctermbg=NONE
  hi @markup.heading guifg=#a5dc01 guibg=NONE guisp=NONE gui=bold cterm=bold ctermfg=148 ctermbg=NONE
  hi @markup.italic guifg=#fe6370 guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=203 ctermbg=NONE
  hi @markup.strong guifg=#fe6370 guibg=NONE guisp=NONE gui=bold cterm=bold ctermfg=203 ctermbg=NONE
  hi @markup.strikethrough guifg=#5a6673 guibg=NONE guisp=NONE gui=strikethrough,italic cterm=strikethrough,italic ctermfg=241 ctermbg=NONE
  hi @markup.raw guifg=#fd8f56 guibg=#1a1e25 guisp=NONE gui=NONE cterm=NONE ctermfg=209 ctermbg=234
  hi @markup.link guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
  hi @markup.link.url guifg=#59c2ff guibg=NONE guisp=NONE gui=underline cterm=underline ctermfg=75 ctermbg=NONE
  hi @markup.list guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi @markup.quote guifg=#85eac9 guibg=NONE guisp=NONE gui=italic cterm=italic ctermfg=115 ctermbg=NONE
  hi @text.title guifg=#a5dc01 guibg=NONE guisp=NONE gui=bold cterm=bold ctermfg=148 ctermbg=NONE
  hi @text.literal guifg=#fd8f56 guibg=#1a1e25 guisp=NONE gui=NONE cterm=NONE ctermfg=209 ctermbg=234
  hi @text.uri guifg=#59c2ff guibg=NONE guisp=NONE gui=underline cterm=underline ctermfg=75 ctermbg=NONE
  hi @diff.plus guifg=#61c33d guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=77 ctermbg=NONE
  hi @diff.minus guifg=#ff5f71 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=203 ctermbg=NONE
  hi TermCursor guifg=#10141c guibg=#e6b450 guisp=NONE gui=NONE cterm=NONE ctermfg=233 ctermbg=179
  hi DiagnosticError guifg=#d95757 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=167 ctermbg=NONE
  hi DiagnosticWarn guifg=#ffb454 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=NONE
  hi DiagnosticInfo guifg=#59c2ff guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=NONE
  hi DiagnosticHint guifg=#5a6673 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=241 ctermbg=NONE
  hi DiagnosticOk guifg=#70bf56 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=106 ctermbg=NONE
  hi DiagnosticVirtualTextError guifg=#d95757 guibg=#241b22 guisp=NONE gui=NONE cterm=NONE ctermfg=167 ctermbg=234
  hi DiagnosticVirtualTextWarn guifg=#ffb454 guibg=#282422 guisp=NONE gui=NONE cterm=NONE ctermfg=215 ctermbg=235
  hi DiagnosticVirtualTextInfo guifg=#59c2ff guibg=#172633 guisp=NONE gui=NONE cterm=NONE ctermfg=75 ctermbg=235
  hi DiagnosticVirtualTextHint guifg=#5a6673 guibg=#181c25 guisp=NONE gui=NONE cterm=NONE ctermfg=241 ctermbg=234
  hi DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#d95757 gui=undercurl cterm=undercurl ctermfg=NONE ctermbg=NONE
  hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#ffb454 gui=undercurl cterm=undercurl ctermfg=NONE ctermbg=NONE
  hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#59c2ff gui=undercurl cterm=undercurl ctermfg=NONE ctermbg=NONE
  hi DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#5a6673 gui=undercurl cterm=undercurl ctermfg=NONE ctermbg=NONE
  hi LspReferenceText guifg=NONE guibg=#212c3e guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=236
  hi LspReferenceRead guifg=NONE guibg=#212c3e guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=236
  hi LspReferenceWrite guifg=NONE guibg=#212c3e guisp=NONE gui=NONE cterm=NONE ctermfg=NONE ctermbg=236
  hi LspInlayHint guifg=#3c4353 guibg=NONE guisp=NONE gui=NONE cterm=NONE ctermfg=238 ctermbg=NONE
  hi LspSignatureActiveParameter guifg=NONE guibg=NONE guisp=NONE gui=bold,underline cterm=bold,underline ctermfg=NONE ctermbg=NONE

  let s:ansi = ['#0a0000', '#e6495a', '#97c142', '#e89d37', '#17acf2', '#c385fe', '#84ceb5', '#ffffff', '#5a6378', '#f07178', '#aad94c', '#ffb454', '#59c2ff', '#d2a6ff', '#95e6cb', '#ffffff']
  for s:i in range(16)
    let g:terminal_color_{s:i} = s:ansi[s:i]
  endfor
else
  let g:terminal_ansi_colors = ['#0a0000', '#e6495a', '#97c142', '#e89d37', '#17acf2', '#c385fe', '#84ceb5', '#ffffff', '#5a6378', '#f07178', '#aad94c', '#ffb454', '#59c2ff', '#d2a6ff', '#95e6cb', '#ffffff']
endif
