#!/bin/sh
# Installs ayu Vivid Space (userChrome.css, userContent.css and the animated
# background) into a Firefox or LibreWolf profile's chrome/ folder.
#
#   sh install.sh                 # LibreWolf's default profile (macOS, Linux, Flatpak)
#   sh install.sh "<profile dir>" # any profile; see about:support -> Profile Folder
#
# Refuses to overwrite a userChrome.css/userContent.css it didn't write.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
marker="Generated by build.ts"

# LibreWolf starts with the profile named in the [Install...] section.
default_profile() {
  for base in \
    "$HOME/Library/Application Support/librewolf" \
    "$HOME/.librewolf" \
    "$HOME/.var/app/io.gitlab.librewolf-community/.librewolf"; do
    [ -f "$base/profiles.ini" ] || continue
    rel=$(awk -F= '/^\[Install/ { f = 1; next } /^\[/ { f = 0 } f && $1 == "Default" { print $2; exit }' "$base/profiles.ini")
    if [ -n "$rel" ]; then
      printf '%s\n' "$base/$rel"
      return
    fi
  done
}

profile=${1:-$(default_profile)}
if [ -z "$profile" ] || [ ! -f "$profile/prefs.js" ]; then
  echo "No profile found. Pass the profile directory (about:support -> Profile Folder)." >&2
  exit 1
fi

for file in "$here/chrome/userChrome.css" "$here/chrome/userContent.css" "$here/img/background.gif"; do
  if [ ! -f "$file" ]; then
    echo "Missing $file" >&2
    exit 1
  fi
done

chrome="$profile/chrome"
for name in userChrome.css userContent.css; do
  if [ -f "$chrome/$name" ] && ! grep -q "$marker" "$chrome/$name"; then
    echo "$chrome/$name exists and wasn't made by this installer; merge it by hand." >&2
    exit 1
  fi
done

mkdir -p "$chrome/img"
cp "$here/img/background.gif" "$chrome/img/background.gif"

# Firefox's own stylesheets use the image through CSS variables, so point to it
# with an absolute file:// URL for this machine.
url="file://$(printf '%s' "$chrome/img/background.gif" | sed 's/%/%25/g; s/ /%20/g')"
sed "s|url(\"img/background.gif\")|url(\"$url\")|g" "$here/chrome/userChrome.css" > "$chrome/userChrome.css"
cp "$here/chrome/userContent.css" "$chrome/userContent.css"

echo "Installed into $chrome"
echo "Next: about:config -> toolkit.legacyUserProfileCustomizations.stylesheets = true,"
echo "      about:addons -> Themes -> enable \"Dark\", then restart the browser."
