#!/bin/sh
# Installs or removes ayu Vivid Space (userChrome.css, userContent.css and the
# animated background) in a Firefox or LibreWolf profile's chrome/ folder.
#
#   sh install.sh                             # install into LibreWolf's default profile
#   sh install.sh "<profile dir>"             # install into any profile
#   sh install.sh --uninstall                 # remove from LibreWolf's default profile
#   sh install.sh --uninstall "<profile dir>" # remove from any profile
#
# The profile dir is shown in about:support -> Profile Folder (called Profile
# Directory on Linux). Default profile detection covers macOS, Linux and the
# LibreWolf Flatpak.
#
# Only touches files it wrote itself (marked "Generated by build.ts"); a
# userChrome.css/userContent.css of your own is never overwritten or removed.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
marker="Generated by build.ts"

# LibreWolf starts with the profile named in the [Install...] section.
default_profile() {
  for base in \
    "$HOME/Library/Application Support/librewolf" \
    "$HOME/.librewolf" \
    "$HOME/.var/app/io.gitlab.librewolf-community/.librewolf"; do
    [ -f "$base/profiles.ini" ] || continue
    rel=$(awk -F= '/^\[Install/ { f = 1; next } /^\[/ { f = 0 } f && $1 == "Default" { print $2; exit }' "$base/profiles.ini")
    if [ -n "$rel" ]; then
      printf '%s\n' "$base/$rel"
      return
    fi
  done
}

mode=install
if [ "${1:-}" = "--uninstall" ]; then
  mode=uninstall
  shift
fi

profile=${1:-$(default_profile)}
if [ -z "$profile" ] || [ ! -f "$profile/prefs.js" ]; then
  echo "No profile found. Pass the profile directory (about:support -> Profile Folder, on Linux: Profile Directory)." >&2
  exit 1
fi
chrome="$profile/chrome"

ours() {
  [ -f "$1" ] && grep -q "$marker" "$1"
}

if [ "$mode" = uninstall ]; then
  removed=0
  for name in userChrome.css userContent.css; do
    if ours "$chrome/$name"; then
      rm "$chrome/$name"
      removed=1
    elif [ -f "$chrome/$name" ]; then
      echo "Kept $chrome/$name (not made by this installer)."
    fi
  done
  if [ "$removed" = 0 ]; then
    echo "ayu Vivid Space is not installed in $profile"
    exit 0
  fi
  rm -f "$chrome/img/background.gif"
  # Clean up folders only if nothing else lives in them.
  rmdir "$chrome/img" 2>/dev/null || true
  rmdir "$chrome" 2>/dev/null || true
  echo "Removed ayu Vivid Space from $chrome"
  echo "Restart the browser. Optionally set toolkit.legacyUserProfileCustomizations.stylesheets"
  echo "back to false in about:config and pick another theme in about:addons."
  exit 0
fi

for file in "$here/chrome/userChrome.css" "$here/chrome/userContent.css" "$here/img/background.gif"; do
  if [ ! -f "$file" ]; then
    echo "Missing $file" >&2
    exit 1
  fi
done

for name in userChrome.css userContent.css; do
  if [ -f "$chrome/$name" ] && ! ours "$chrome/$name"; then
    echo "$chrome/$name exists and wasn't made by this installer; merge it by hand." >&2
    exit 1
  fi
done

mkdir -p "$chrome/img"
cp "$here/img/background.gif" "$chrome/img/background.gif"

# Firefox's own stylesheets use the image through CSS variables, so point to it
# with an absolute file:// URL for this machine.
url="file://$(printf '%s' "$chrome/img/background.gif" | sed 's/%/%25/g; s/ /%20/g')"
sed "s|url(\"img/background.gif\")|url(\"$url\")|g" "$here/chrome/userChrome.css" > "$chrome/userChrome.css"
cp "$here/chrome/userContent.css" "$chrome/userContent.css"

echo "Installed into $chrome"
echo "Next: about:config -> toolkit.legacyUserProfileCustomizations.stylesheets = true,"
echo "      about:addons -> Themes -> enable \"Dark\", then restart the browser."
