// Custom CSS for the Kagi search engine (kagi.com → Settings → Appearance →
// Custom CSS) in kagi/. One file for both Kagi themes: ayu Vivid Light by
// default, ayu Vivid Dark when Kagi's Dark or Moon Dark theme is selected.
//
// Based on a Monokai custom CSS; each Monokai color is replaced by its ayu
// counterpart: red → accent yellow (hover, active), purple → visited,
// green → summary link. Result titles are underlined on hover only. In dark
// they use ayu's Markdown link color (syntax.tag), calmer than the entity blue;
// in light, the entity blue reads better on the white page.
import * as ayu from 'ayu'
import {
  channels,
  hex,
  NAME,
  oklabToSrgb,
  type Scheme,
  SLUG,
  solid,
  srgbToOklab,
  toHex,
  vivid,
  writeText
} from './shared.ts'

// Kagi puts the active theme as a class on the page.
const DARK_THEMES = ['.theme_dark', '.theme_moon_dark']

const luminance = (hexColor: string) => {
  const lin = (c: number) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
  const [r, g, b] = channels(hexColor).slice(0, 3).map(lin)
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}
const contrast = (a: string, b: string) => {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}

// ayu Light's syntax colors are made for code and too faint for links on a
// white page. Lowers OKLCH lightness (hue and chroma kept) until the color
// reaches 4.5:1 against the background, the usual minimum for body text.
const readable = (hexColor: string, bg: string, min = 4.5) => {
  const [L, a, b] = srgbToOklab(channels(hexColor).slice(0, 3))
  let color = hexColor
  for (let l = L; contrast(color, bg) < min && l > 0; l -= 0.01) color = toHex(oklabToSrgb([l, a, b]))
  return color
}

const palette = (s: Scheme) => {
  const background = hex(s.editor.bg)
  const text = (c: string) => readable(c, background)
  const accent = hex(s.common.accent.tint)
  const dark = s === ayu.dark
  // Search field: ayu's panel surface (a step off the page) instead of Kagi's grey.
  const searchBg = dark ? hex(s.ui.panel.bg) : hex(s.ui.popup.bg)
  return {
    background,
    'search-bg': searchBg,
    'search-border': solid(s.ui.line.hex(), searchBg),
    foreground: text(hex(s.editor.fg)),
    comment: hex(s.syntax.comment),
    // Fills: buttons, active search mode, toggles, glow.
    accent,
    // Text and icons on an accent fill.
    'on-accent': contrast(background, accent) >= 4.5 ? background : hex(ayu.dark.ui.bg),
    // Text colors.
    'accent-text': text(accent),
    blue: text(hex(vivid(s.syntax.entity))),
    purple: text(hex(vivid(s.syntax.constant))),
    green: text(hex(vivid(s.syntax.string))),
    orange: text(hex(vivid(s.syntax.keyword))),
    // Titles are large text, so 3:1 is enough and the blue can stay brighter.
    title: dark ? text(hex(s.syntax.tag)) : readable(hex(vivid(s.syntax.entity)), background, 3)
  }
}

// Our variables plus the Kagi variables they replace. Kagi's are written with
// literal values in each block (not var()), because a var() is resolved where
// it's declared: if Kagi puts the theme class below :root, a :root-level
// reference would keep the light value.
const vars = (p: ReturnType<typeof palette>, indent: string) =>
  [
    ...Object.entries(p).map(([k, v]) => `--ayu-${k}: ${v};`),
    '',
    `--search-result-title: ${p.title};`,
    '--result-item-title-border: transparent;',
    `--color-search-input: ${p['search-bg']};`,
    `--input-bg: ${p['search-bg']};`,
    `--color-search-input-border: ${p['search-border']};`,
    `--app-search-text: ${p.foreground};`
  ].map((l) => (l ? indent + l : l)).join('\n')

// theme-color meta value for Kagi's settings (browser toolbar tint on mobile
// and Safari): the page background, so the browser blends into the page.
export const kagiThemeColors = () => ({ light: hex(ayu.light.editor.bg), dark: hex(ayu.dark.editor.bg) })

const kagiCss = () => {
  const light = palette(ayu.light)
  const dark = palette(ayu.dark)
  const meta = kagiThemeColors()

  return `/* ${NAME} for Kagi: paste into kagi.com \u2192 Settings \u2192 Appearance \u2192 Custom CSS.
 * Light colors with Kagi's light themes, dark colors with Dark / Moon Dark.
 * Theme color (Settings \u2192 Appearance): light ${meta.light}, dark ${meta.dark}.
 * Generated by build.ts from the ayu palette. Don't edit by hand. */

:root {
${vars(light, '  ')}
}

${DARK_THEMES.join(',\n')} {
${vars(dark, '  ')}
}

body {
  font-family: sans-serif;
  font-size: 16px;
  background-color: var(--ayu-background);
  color: var(--ayu-foreground);
}

/* Search field: ayu accent outline while typing */
.search-form .search-input-container:focus-within {
  border-color: var(--ayu-accent);
}

/* Search result titles */
.__sri-title .__sri_title_link {
  color: var(--search-result-title);
  border-bottom: 1px solid var(--result-item-title-border);
}

.__sri-title .__sri_title_link:visited {
  color: var(--ayu-purple);
}

.__sri-title .__sri_title_link:hover {
  color: var(--ayu-accent-text);
  border-bottom: 1px solid var(--ayu-accent-text);
}

/* Buttons */
.btn.--yellow {
  background-color: var(--ayu-accent);
  border: 1px solid var(--ayu-accent);
  color: var(--ayu-on-accent);
  transition: ease 150ms;
}

.btn.--yellow:hover {
  background-color: var(--ayu-blue);
  border: 1px solid var(--ayu-accent);
  color: var(--ayu-background);
  transform: scale(1.05);
}

/* Outer glow on hover */
.btn.--yellow:hover::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border-radius: inherit;
  box-shadow: 0 0 1rem 0.5rem var(--ayu-accent);
  opacity: 0.6;
}

/* Hide unused elements */
.doggo-sit, .doggo-left, #eyes-on, #eyes-off {
  display: none;
}

/* Category buttons */
.landing-category-select button.n_se.--active,
.landing-category-select button.n_se:hover {
  border-bottom: 2px solid var(--ayu-purple);
}

/* Grouped search result titles */
.__srgi-title a {
  color: var(--search-result-title);
  border-bottom: 1px solid var(--result-item-title-border);
  font-size: 1.5rem;
}

.__srgi-title a:visited {
  color: var(--ayu-purple);
}

.__srgi-title a:hover {
  color: var(--ayu-accent-text);
  border-bottom: 1px solid var(--ayu-accent-text);
}

/* Dropdowns */
.dropdown .dd-toggle-label:hover,
.k_ui_dropdown .k_ui_dropdown_first_item:hover {
  color: var(--ayu-accent-text);
}

/* Summary link */
._0_summarize_link a {
  color: var(--ayu-green);
}

._0_summarize_link a:hover {
  color: var(--ayu-accent-text);
}

/* All links on hover */
a:hover {
  color: var(--ayu-accent-text);
}

/* Active search modes */
._0_d_info_ranking.k_ui_btn_group .search_mode_box_s input:checked + a.k_ui_btn,
._0_sri-w-highlight .search_mode_box_s a.searchResultAnswer,
.search_mode_box_s ._0_d_info_ranking.k_ui_btn_group input:checked + a.k_ui_btn,
.search_mode_box_s ._0_sri-w-highlight a.searchResultAnswer,
.search_mode_box_s a.--active,
.search_mode_box_s a._0_sri-w-highlight.box,
.search_mode_box_s a.box:hover {
  background-color: var(--ayu-accent);
  border: var(--ayu-accent);
  color: var(--ayu-on-accent);
}

._0_results_summary_links ol a:hover {
  color: var(--ayu-accent-text) !important;
}

.k_ui_toggle_switch.--enabled .k_ui_toggle_switch_bar {
  background-color: var(--ayu-accent);
}
`
}

export const build = () => {
  writeText(`kagi/${SLUG}.css`, kagiCss())
  return 'kagi: custom CSS (light + dark)'
}
