// Terminal color schemes in terminal/: iTerm2 (.itermcolors) and Ghostty, for
// ayu Vivid Dark and Light. Colors are read from the generated Zed theme, so
// they match Zed's terminal and COSMIC Terminal exactly.
import * as ayu from 'ayu'
import { channels, NAME, oklabToSrgb, solid, srgbToOklab, toHex, type Variant, writeText } from './shared.ts'
import { theme, type ZedTheme } from './zed.ts'

const ANSI = ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white'] as const

export type TerminalColors = {
  background: string
  foreground: string
  bold: string
  cursor: string
  cursorText: string
  selection: string
  link: string
  // 0-7 normal, 8-15 bright, as in every terminal's 16-color palette.
  palette: string[]
}

const lighten = (hexColor: string, dL: number) => {
  const [L, a, b] = srgbToOklab(channels(hexColor).slice(0, 3))
  return toHex(oklabToSrgb([L + dL, a, b]))
}

// Changes against the Zed/COSMIC terminal colors, tested in Ghostty. Dark only;
// Light keeps the generated values. Meant to move into zed.ts with the next
// Zed version, so all terminals match again.
//   white: ayu's text color instead of #ffffff, so normal and bright white differ
//   green: ayu's string green instead of the darker terminal green, and a
//          lighter bright green (same hue), so the two greens are easy to tell apart
const tweakDark = (palette: string[], foreground: string) => {
  const green = palette[10]
  palette[2] = green
  palette[10] = lighten(green, 0.06)
  palette[7] = foreground
}

export const terminalColors = (z: ZedTheme): TerminalColors => {
  const st = z.style as unknown as Record<string, string>
  const background = st['terminal.background']
  const palette = [
    ...ANSI.map((n) => st[`terminal.ansi.${n}`]),
    ...ANSI.map((n) => st[`terminal.ansi.bright_${n}`])
  ]
  if (z.appearance === 'dark') tweakDark(palette, st['terminal.foreground'])
  return {
    background,
    foreground: st['terminal.foreground'],
    bold: st['terminal.bright_foreground'],
    cursor: z.style.players[0].cursor,
    cursorText: background,
    selection: solid(z.style.players[0].selection, background),
    link: st['text.accent'],
    palette
  }
}

const itermColor = (key: string, hexColor: string) => {
  const [r, g, b] = channels(hexColor)
  return `\t<key>${key}</key>
\t<dict>
\t\t<key>Alpha Component</key>
\t\t<real>1</real>
\t\t<key>Blue Component</key>
\t\t<real>${b}</real>
\t\t<key>Color Space</key>
\t\t<string>sRGB</string>
\t\t<key>Green Component</key>
\t\t<real>${g}</real>
\t\t<key>Red Component</key>
\t\t<real>${r}</real>
\t</dict>`
}

export const itermcolors = (c: TerminalColors) => {
  const entries: [string, string][] = [
    ...c.palette.map((h, i): [string, string] => [`Ansi ${i} Color`, h]),
    ['Background Color', c.background],
    ['Bold Color', c.bold],
    ['Cursor Color', c.cursor],
    ['Cursor Text Color', c.cursorText],
    ['Foreground Color', c.foreground],
    ['Link Color', c.link],
    ['Selected Text Color', c.foreground],
    ['Selection Color', c.selection]
  ]
  entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
${entries.map(([k, h]) => itermColor(k, h)).join('\n')}
</dict>
</plist>
`
}

export const ghostty = (name: string, c: TerminalColors) =>
  [
    `# ${name} for Ghostty. Generated by build.ts from the ayu palette; don't edit by hand.`,
    ...c.palette.map((h, i) => `palette = ${i}=${h}`),
    `background = ${c.background}`,
    `foreground = ${c.foreground}`,
    `cursor-color = ${c.cursor}`,
    `cursor-text = ${c.cursorText}`,
    `selection-background = ${c.selection}`,
    `selection-foreground = ${c.foreground}`
  ].join('\n') + '\n'

export const build = () => {
  const variants: Variant[] = ['dark', 'light']
  for (const v of variants) {
    const z = theme(ayu[v], v)
    const c = terminalColors(z)
    writeText(`terminal/iterm2/${z.name}.itermcolors`, itermcolors(c))
    writeText(`terminal/ghostty/${z.name}`, ghostty(z.name, c))
  }
  return `terminal: iTerm2 and Ghostty (${NAME} Dark, Light)`
}
